---
title: "統計学2"
subtitle: "課題3"
author: "1100001 ☆矢☆内☆勇☆生☆" # 自分の学籍番号 + 氏名に修正すること
date: today
format:
  pdf:
    pdf-engine: lualatex
    documentclass: ltjsarticle
    fontsize: 10.5pt
    linestretch: 1.15
knitr: 
  opts_chunk: 
    echo: true
    message: false
    warning: true
    error: true
    dev: ragg_png
    dpi: 300
    fig-align: center
---

## 注意事項

- **提出期限：**2025年2月16日（日）23時59分（日本時間）
- **提出方法：**KUTLMSの「課題の提出場所」の「課題3」にファイルを提出する。
- 本Quarto文書をrenderして作った**PDFファイル**を提出しなさい。
  - Quarto文書をrenderしたPDFファイル以外は受け付けない。
- 提出するファイル名は、**`stat2_hw3_自分の学籍番号.pdf`**とすること。
- 実験結果を説明する文章がこのレポートの本体であり、計算結果や図は説明のためのを補助手段であることを忘れずにレポートを書きなさい。

\clearpage

## 課題3-1：母平均の推定（$\sigma$が未知の場合）

**問題：**平均が$\mu$の母集団から$N=10$の標本$(x_1, x_2, \dots, x_{10})$を抽出したところ、以下のデータが得られた。

|$x_1$ |  $x_2$ |  $x_3$ | $x_4$ | $x_5$ | $x_6$ | $x_7$ | $x_8$ | $x_9$ | $x_{10}$ |
| --: | --: |  --: |  --: |  --: |  --: |  --: |  --: |  --: |  --: |  
| 1.2 | 0.5 | 0.9 | 0.7 | 0.6 | 0.9 | 0.7 | 0.4 | 1.4 | 1.4 | 

　このとき$\mu$の（1）点推定値、（2）95%信頼区間、（3）77%信頼区間をそれぞれ求めなさい。

<!-- この行の下から課題3-1のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題3-1のコードおよび文章を入れる。 -->

\clearpage

## 課題 3-2：仮説検定 (1)

**問題：**K工科大学とM工科大学の学生が、どの程度統計学に興味を持っているか調べたい。K工科大学から15人をランダムに選び、統計学に対する興味の強さを100点満点で評価してもらった。同様に、M工科大学から12人をランダムに選び、統計学に対する興味の強さを100点満点で評価してもらった。結果は以下のとおりである。

```{r}
K <- c(80, 90, 78, 82, 23,
       67, 78, 84, 99, 72,
       84, 87, 75, 66, 91)

M <- c(89, 78, 67, 56, 43, 
       53, 23, 97, 67, 65, 
       42, 43)
```

　この調査結果から、K工科大学とM工科大学の学生の間で、統計学に対する興味の強さに違いがあるか検討したい。そのために、以下の各問に答えなさい。ただし、有意水準は5%とする（$\alpha = 0.05$）。

1. 帰無仮説と対立仮説は何か？それぞれ述べなさい。
1. 評価の差の点推定値はいくつ？
1. 検定統計量はいくつ？
1. 検定の臨界値はいくつ？
1. 検定の結論は？

<!-- この行の下から課題3-2のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題3-2のコードおよび文章を入れる。 -->

\clearpage

## 課題 3-3：仮説検定 (2)

**問題：**あるラーメン屋の豚骨ラーメンと塩ラーメンを10人に食べてもらい、それぞれのラーメンを10点満点（0点から10点まで1点刻み）で評価してもらった。評価の結果は下の表の通りである。日本に住む人全員を母集団と考えたとき、豚骨ラーメンと塩ラーメンの評価に違いがあるかどうか、有意水準5%で検定したい（$\alpha = 0.05$）。このとき、以下の各問に答えよ。

| 評価者|1|2|3|4|5|6|7|8| 9|10|
| :---: |:---: |:---: |:---: |:---: |:---: |:---: |:---: |:---: |:---: |:---: |
| 豚骨  |8|6|5|6|1|5|3|7| 8| 4|
| 塩    |6|7|8|3|2|8|4|2|10| 7|

1. 帰無仮説と対立仮説は何か？それぞれ述べなさい。
1. 評価の差の平均値はいくつ？
1. 検定統計量はいくつ？
1. 検定の臨界値はいくつ？
1. 検定の結論は？

<!-- この行の下から課題3-3のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題3-3のコードおよび文章を入れる。 -->

\clearpage

## 課題 3-4：二変数の関係

**問題：**`data`フォルダー内の`bivariate_13pairs.csv`というデータセット[^dataset]には、全部で26個の変数が保存されている。26個の変数は、13組の$(x, y)$であり、`x_1`と`y_1`がペア、`x_2`と`y_2`がペア、というように、13組の2変数で構成されている。変数はすべて量的な変数である。

　これら13組のペアのそれぞれについて2変数の間の関係を調べなさい（つまり13組の関係を調べる）。そして、全体としてこの課題からどのような教訓が得られるか、文章にまとめなさい。

[^dataset]: このデータは、[Alberto Cairo](https://albertocairo.com/)が提供する有名なデータを授業用に整理したものである

<!-- この行の下から課題3-4のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題3-4のコードおよび文章を入れる。 -->
