---
title: "統計学2"
subtitle: "課題2"
author: "1100001 佐藤太郎" # 自分の学籍番号 + 氏名に修正すること
date: today
format:
  pdf:
    pdf-engine: lualatex
    documentclass: ltjsarticle
    fontsize: 10.5pt
    linestretch: 1.15
    include-in-header:
      text: |
        \usepackage[haranoaji, deluxe]{luatexja-preset}
        \renewcommand{\textbf}[1]{\textgt{#1}}
knitr: 
  opts_chunk: 
    echo: true
    message: false
    warning: true
    error: true
    dev: ragg_png
    dpi: 300
    fig-align: center
---

## 注意事項

- **提出期限：**2025年2月16日（日）23時59分（日本時間）
- **提出方法：**KUTLMSの「課題の提出場所」の「課題2」にファイルを提出する。
- 本Quarto文書をrenderして作った**PDFファイル**を提出しなさい。
  - Quarto文書をrenderしたPDFファイル以外は受け付けない。
- 提出するファイル名は、**`stat2_hw2_自分の学籍番号.pdf`**とすること。
- 実験結果を説明する文章がこのレポートの本体であり、計算結果や図は説明のためのを補助手段であることを忘れずにレポートを書きなさい。

\clearpage

## 課題2-1：母集団と標本

**問題：**実習資料の「6.3 実習課題」を実行し、結果をまとめなさい。

<!-- この行の下から課題2-1のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題2-1のコードおよび文章を入れる。 -->

\clearpage

## 課題 2-2：大数の法則

**問題：**実習資料の「7.3 実習課題」を実行し、結果をまとめなさい。

<!-- この行の下から課題2-2のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題2-2のコードおよび文章を入れる。 -->

\clearpage

## 課題 2-3：標本分布

**問題：**日本の成人女性の身長が、平均160cm、標準偏差6cmの正規分布に従っていると仮定する。このとき、標本サイズ（$N$）が10、50、100のそれぞれの場合について、標本抽出を繰り返し、標本平均がどのように分布するか調べなさい。シミュレーションの繰り返し回数は5,000回以上で自由に設定してよい。

1. それぞれの標本サイズで、標本平均の分布を示すヒストグラムを作りなさい。
1. それぞれの標本サイズで、標本平均の平均値を計算しなさい。
1. それぞれの標本サイズで、標準誤差を計算しなさい。
1. 最後に、今回の課題からどのようなことを学んだか、1段落程度で述べなさい。

<!-- この行の下から課題2-3のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題2-3のコードおよび文章を入れる。 -->

\clearpage

## 課題 2-4：母平均の推定（$\sigma$が既知の場合）

**問題：**平均が$\mu$、標準偏差が$\sigma = 0.5$の母集団から$N=10$の標本$(x_1, x_2, \dots, x_{10})$を抽出したところ、以下のデータが得られた。

|$x_1$ |  $x_2$ |  $x_3$ | $x_4$ | $x_5$ | $x_6$ | $x_7$ | $x_8$ | $x_9$ | $x_{10}$ |
| --: | --: |  --: |  --: |  --: |  --: |  --: |  --: |  --: |  --: |  
| 1.2 | 0.5 | 0.9 | 0.7 | 0.6 | 0.9 | 0.7 | 0.4 | 1.4 | 1.4 | 

このとき$\mu$の（1）点推定値、（2）95%信頼区間、（3）70%信頼区間をそれぞれ求めなさい。

<!-- この行の下から課題2-4のコードおよび文章を入れる。 -->

にゃー

<!-- この行の上まで課題2-4のコードおよび文章を入れる。 -->